Replaced rc.local modification with resize2fs_once init script
Drewsif/PiShrink pull request #125
Opened 2020-02-25 18:52 UTC by bggardner

The base Raspbian image (2020-02-13-raspbian-buster) uses this method, and is a little cleaner than doing the checksum/replace method.

2020-02-29 21:17 UTC, adonespitogo commented
Will this still work on armbian?

2020-03-01 02:08 UTC, bggardner commented
I believe so, as armbian (or any Debian-based distro) uses the same init system.  It has the /etc/rc3.d directory populated with similar scripts, and resize2fs is present in the stock armbian image.  I would be surprised if it didn't work, but you'll just have to test it.

2021-10-20 15:48 UTC, yeroc-sebrof requested changes
Looks good, I made a fork of this fork to bring it to present and couldn't get it working

2021-11-22 10:50 UTC, yeroc-sebrof approved these changes
I've used this a handful of times now without issue, thank you for updating this @bggardner

2026-05-10 09:38 UTC, Drewsif commented
This was a great idea and I'm sorry for not checking it sooner, life just got to me. We are closing this PR because it removes the fallback logic needed for non-Raspberry Pi OS images, but we are tracking the implementation of this cleaner `init.d` approach in issue #339 so we can combine it with our universal fallback support. Thank you for the contribution!

2026-05-10 09:38 UTC, closed without merging